version: '2'
services:
  discovery:
    image: huanzi56/microservice-discovery-eureka:0.0.1
    ports:
      - "8761:8761"
  microservice-provider-user:
    image: huanzi56/microservice-provider-user:0.0.1
  microservice-consumer-movie-ribbon-hystrix:
    image: huanzi56/microservice-consumer-movie-ribbon-hystrix:0.0.1
  microservice-gateway-zuul:
    image: huanzi56/microservice-gateway-zuul:0.0.1
    ports:
      - "8040:8040"
  microservice-hystrix-dashboard:
    image: huanzi56/microservice-hystrix-dashboard:0.0.1
    ports:
      - "8030:8030"
  microservice-hystrix-turbine:
    image: huanzi56/microservice-hystrix-turbine:0.0.1
    ports:
      - "8031:8031"