server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://admin:xylx1.t@discovery:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: microservice-consumer-movie-ribbon-hystrix,microservice-provider-user
  clusterNameExpression: "'default'"